//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationTool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResource_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigurationTool.Resources.ApplicationResource.de", typeof(ApplicationResource_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du neue Benutzer hinzufügen. Bitte füge die mail adresse, der person die die du hinzufügen möchtest unten ein..
        /// </summary>
        internal static string AddNewMembers {
            get {
                return ResourceManager.GetString("AddNewMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Seite.
        /// </summary>
        internal static string AdminPage {
            get {
                return ResourceManager.GetString("AdminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie müssen den AGBs zustimmen!.
        /// </summary>
        internal static string AgreeToTOS {
            get {
                return ResourceManager.GetString("AgreeToTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist bereits eingeloggt!.
        /// </summary>
        internal static string AlreadyLoggedIn {
            get {
                return ResourceManager.GetString("AlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antwort.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du musst eine Email eingeben!.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email erforderlich!.
        /// </summary>
        internal static string EmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen Antwort mit mindestens 10 Buchstaben ein.
        /// </summary>
        internal static string ErrorTextAnswer {
            get {
                return ResourceManager.GetString("ErrorTextAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie mindestens 10 Buchstaben ein.
        /// </summary>
        internal static string ErrorTextInputQuestionManagment {
            get {
                return ResourceManager.GetString("ErrorTextInputQuestionManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen Frage mit mindestens 10 Buchstaben ein.
        /// </summary>
        internal static string ErrorTextQuestion {
            get {
                return ResourceManager.GetString("ErrorTextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo und Willkommen bei Rezep.
        /// </summary>
        internal static string Greating {
            get {
                return ResourceManager.GetString("Greating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich stimme den AGBs zu!.
        /// </summary>
        internal static string IAgreeToTOS {
            get {
                return ResourceManager.GetString("IAgreeToTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Nachname ist erforderlich!.
        /// </summary>
        internal static string LastNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LastNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Name ist erfoderlich.
        /// </summary>
        internal static string NameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast nicht die nötige berechtigung um auf diese Seite zu zugreifen..
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch nicht implementiert!.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort muss mindestens einen Großbuchstaben enthalten!.
        /// </summary>
        internal static string PasswordCapitalLetter {
            get {
                return ResourceManager.GetString("PasswordCapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Passwort stimmt nicht überein!.
        /// </summary>
        internal static string PasswordConfirmErrorMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte bestätige dein Passwort!.
        /// </summary>
        internal static string PasswordConfirmRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort muss mindestens eine Ziffer enthalten!.
        /// </summary>
        internal static string PasswordDigit {
            get {
                return ResourceManager.GetString("PasswordDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort muss mindestens die Länge 8 haben!.
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort muss mindestens einen Kleinbuchstaben enthalten!.
        /// </summary>
        internal static string PasswordLowercaseLetter {
            get {
                return ResourceManager.GetString("PasswordLowercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwörter stimmen nicht überein!.
        /// </summary>
        internal static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du musst ein Passwort eingeben!.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Passwort ist erforderlich!.
        /// </summary>
        internal static string PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie ein sicheres Passwort!.
        /// </summary>
        internal static string PasswordStrength {
            get {
                return ResourceManager.GetString("PasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peppereinstellungen.
        /// </summary>
        internal static string PepperSettings {
            get {
                return ResourceManager.GetString("PepperSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frage.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragen die schon beantwortet wurden.
        /// </summary>
        internal static string QuestionListTitle {
            get {
                return ResourceManager.GetString("QuestionListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche ein Frage.
        /// </summary>
        internal static string QuestionScreenBar {
            get {
                return ResourceManager.GetString("QuestionScreenBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragenverwaltung.
        /// </summary>
        internal static string QuestionsManagement {
            get {
                return ResourceManager.GetString("QuestionsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer regestrieren.
        /// </summary>
        internal static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholen Sie das Passwort!.
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle einen Sprache aus.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einreichen.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen bei Rezep. Auf dieser Website können Sie Ihre Rezep-Einstellungen ändern oder Ihre Fragen verwalten..
        /// </summary>
        internal static string WelcomeMessageText {
            get {
                return ResourceManager.GetString("WelcomeMessageText", resourceCulture);
            }
        }
    }
}
