//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationTool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigurationTool.Resources.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can add new members. Please enter the mail address of the person you want to add. They will get a mail and log in..
        /// </summary>
        public static string AddNewMembers {
            get {
                return ResourceManager.GetString("AddNewMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Page.
        /// </summary>
        public static string AdminPage {
            get {
                return ResourceManager.GetString("AdminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to your TOS!.
        /// </summary>
        public static string AgreeToTOS {
            get {
                return ResourceManager.GetString("AgreeToTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already, logged in!.
        /// </summary>
        public static string AlreadyLoggedIn {
            get {
                return ResourceManager.GetString("AlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required!.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is required!.
        /// </summary>
        public static string EmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a answer with a minimum of 10 characters.
        /// </summary>
        public static string ErrorTextAnswer {
            get {
                return ResourceManager.GetString("ErrorTextAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleace enter at least 10 characters.
        /// </summary>
        public static string ErrorTextInputQuestionManagment {
            get {
                return ResourceManager.GetString("ErrorTextInputQuestionManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a question with a minimum of 10 characters.
        /// </summary>
        public static string ErrorTextQuestion {
            get {
                return ResourceManager.GetString("ErrorTextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Welcome to Rezep.
        /// </summary>
        public static string Greating {
            get {
                return ResourceManager.GetString("Greating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the TOS!.
        /// </summary>
        public static string IAgreeToTOS {
            get {
                return ResourceManager.GetString("IAgreeToTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last name is required!.
        /// </summary>
        public static string LastNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LastNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first name is required!.
        /// </summary>
        public static string NameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you&apos;re not authorized to access this page..
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT IMPLEMENTED! (yet).
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one capital letter!.
        /// </summary>
        public static string PasswordCapitalLetter {
            get {
                return ResourceManager.GetString("PasswordCapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your passwords do not match!.
        /// </summary>
        public static string PasswordConfirmErrorMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password!.
        /// </summary>
        public static string PasswordConfirmRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit.
        /// </summary>
        public static string PasswordDigit {
            get {
                return ResourceManager.GetString("PasswordDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least of length 8!.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter!.
        /// </summary>
        public static string PasswordLowercaseLetter {
            get {
                return ResourceManager.GetString("PasswordLowercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match!.
        /// </summary>
        public static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is required!.
        /// </summary>
        public static string PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a strong password!.
        /// </summary>
        public static string PasswordStrength {
            get {
                return ResourceManager.GetString("PasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pepper settings.
        /// </summary>
        public static string PepperSettings {
            get {
                return ResourceManager.GetString("PepperSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Management.
        /// </summary>
        public static string QuestionsManagement {
            get {
                return ResourceManager.GetString("QuestionsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register User.
        /// </summary>
        public static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the password!.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Rezep. In on this website you can change your Rezep-Settings or manage your questions..
        /// </summary>
        public static string WelcomeMessageText {
            get {
                return ResourceManager.GetString("WelcomeMessageText", resourceCulture);
            }
        }
    }
}
