name: Build and Deploy C# Project to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Publish Project
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Build Docker Image
      working-directory: .
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/herbert-configtool:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/herbert-configtool:latest